# Generated by Django 5.2 on 2026-04-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='books/'),
        ),
    ]
